### ISSUE TITLE
beta14安装后报错

### ISSUE THREAD

**Issue by Marchccc** [NomisCZ/flarum-ext-auth-wechat#11]
```
PHP Fatal error:  Uncaught FastRoute\BadRouteException: Static route "/auth/wechat" is shadowed by previously defined variable route "/auth/([^/]+)" for method "GET" in /www/wwwroot/flarum/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php:64
Stack trace:
#0 /www/wwwroot/flarum/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php(18): FastRoute\DataGenerator\RegexBasedAbstract->addStaticRoute('GET', Array, Object(Closure))
#1 /www/wwwroot/flarum/vendor/flarum/core/src/Http/RouteCollection.php(69): FastRoute\DataGenerator\RegexBasedAbstract->addRoute('GET', Array, Object(Closure))
#2 /www/wwwroot/flarum/vendor/flarum/core/src/Extend/Routes.php(82): Flarum\Http\RouteCollection->addRoute('GET', '/auth/wechat', 'auth.wechat', Object(Closure))
#3 /www/wwwroot/flarum/vendor/illuminate/container/Container.php(1102): Flarum\Extend\Routes->Flarum\Extend\{closure}(Object(Flarum\Http\RouteCollection), Object(Illuminate\Container\Container))
#4 /www/wwwroot/flarum/vendor/illuminate/container/Container.php(1048):  in /www/wwwroot/flarum/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php on line 64

Fatal error: Uncaught FastRoute\BadRouteException: Static route "/auth/wechat" is shadowed by previously defined variable route "/auth/([^/]+)" for method "GET" in /www/wwwroot/flarum/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php:64
Stack trace:
#0 /www/wwwroot/flarum/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php(18): FastRoute\DataGenerator\RegexBasedAbstract->addStaticRoute('GET', Array, Object(Closure))
#1 /www/wwwroot/flarum/vendor/flarum/core/src/Http/RouteCollection.php(69): FastRoute\DataGenerator\RegexBasedAbstract->addRoute('GET', Array, Object(Closure))
#2 /www/wwwroot/flarum/vendor/flarum/core/src/Extend/Routes.php(82): Flarum\Http\RouteCollection->addRoute('GET', '/auth/wechat', 'auth.wechat', Object(Closure))
#3 /www/wwwroot/flarum/vendor/illuminate/container/Container.php(1102): Flarum\Extend\Routes->Flarum\Extend\{closure}(Object(Flarum\Http\RouteCollection), Object(Illuminate\Container\Container))
#4 /www/wwwroot/flarum/vendor/illuminate/container/Container.php(1048):  in /www/wwwroot/flarum/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php on line 64
```

**Comment by NomisCZ** [comment]
🔎 **Error:** Flarum encountered a boot error (FastRoute\BadRouteException) Static route "/auth/wechat" is shadowed by previously defined variable route "/auth/([^/]+)" for method "GET"
- 👉 **Update  [FoF OAuth extension](https://discuss.flarum.org/d/25182-friendsofflarum-oauth), issue: https://github.com/FriendsOfFlarum/oauth/pull/12**
